name: Smoke API tests using Postman CLI

on:
  workflow_dispatch:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMANAPIKEY }}
      - name: Run API tests
        run: |
          postman collection run "17595103-a9815759-fcc7-49ec-85f4-2567e2e2c0a9" -e "17595103-013eb0eb-5065-4c86-aa88-8363e27ede08" \
          -r cli,json,junit,html \
          --reporter-json-export postman-cli-reports/report.json \
          --reporter-junit-export postman-cli-reports/report.xml \
          --reporter-html-export postman-cli-reports/report.html

      - name: 📊 Upload Artifact Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: postman-cli-reports
          retention-days: 10

      - name: 🚀 Deploy Mocha Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages #? the branch used for the GitHub Pages content.
          destination_dir: tests #? this is the directory inside the gh-pages branch where the report.html will be saved.
          publish_dir: postman-cli-reports/report.html #? the directory to be published.
          keep_files: true #? true is required to work properly
